### ISSUE TITLE
Doc portal workshop -bug on Windows/Chrome

### ISSUE THREAD

**Issue by sabineberland** [derberg/Documenting-REST-API---Workshop-Script#4]
When trying to launch the documentation portal (first steps) on Windows... in Chrome, I get an error "page not found"; while it works on Edge (nice look and feel with images). 
Same result also after completing the workshop: local portal in Edge is visible, while it produces an error in Chrome. (See attached file)

versions used: Windows 10 Home edition, 64 bits
Chrome v 55.0.2883.87 m (64-bit)
Microsoft Edge 38.14393.0.0
Python 3.5 (32 bit)
Atom 1.12.7
GIT GUI version 0.21.GITGUI / 2.11.0.windows.1 (came with GIT CMD and GIT Bash)
Node.js = downloaded a version 6.9.2 (x64)
GitHub Desktop v3.3.3.0 

<img width="1920" alt="workshop_result_20161213_edgevschrome" src="https://cloud.githubusercontent.com/assets/22657149/21144367/aad47080-c14a-11e6-9017-7121bd09f83f.png">

**Comment by derberg** [comment]
Hi, thanks for reporting it
You have an error in the URL in chrome, "dot" in the user name.
Please check without it. I tried https://sabineberland.github.io/ in chrome and it works well

**Comment by sabineberland** [comment]
OMG. ok, so you can close this issue I guess...
Thanks for your sharp eyes


Cordialement, / Best regards,

---
*Sabine BERLAND | Mirakl*
*Technical Writer*
*- available on Mondays, Tuesdays, Thursdays, Fridays -*
Office: +33 (0)1 72 31 62 00
10, rue de l'Amiral Hamelin, 75016 Paris - www.mirakl.com

*Mirakl*
The Global Leader in Online Marketplace Platforms
Helping International Retailers Better Serve More Customers. Simply, Cost
Effectively.

Best Buy, Harvey Nichols, Woolworths, Galeries Lafayette, El Corte Ingles,
Auchan, Game, Darty...


2016-12-13 16:23 GMT+01:00 Lukasz Gornicki <notifications@github.com>:

**Comment by derberg** [comment]
After what I was doing with "commas" during the webinar, "dots" could also show up :)
